local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 5
  height: 5
  resolution: 0.10
  transform_tolerance: 0.5

  plugins:
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   
